version: "2"
services:
  app:
    build: ./
    container_name: "Flask_App"
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # EMAIL_VERIFIER_KEY: 'at_d2rnczuTQlRMWTq5qElyv5fr4nwYi'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro